package com.googlecode.tawus.annotations;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * This annotation when placed on a bean field makes it non-updatable for the
 * presentation layer. The means it will be presented as read-only rather than
 * an input field in a form generated by
 * {@link com.googlecode.tawus.components.EntityEditor}
 * 
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD })
public @interface NonUpdatable
{

}
